// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDESxNXaB4n2pF9ur4uJ1g1O9272N1jTPc',
    appId: 'YOURAPPID',
    messagingSenderId: '98445333419',
    projectId: 'pushnotificationtest2023',
    authDomain: 'pushnotificationtest2023.firebaseapp.com',
    storageBucket: 'pushnotificationtest2023.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVjSMzgqNKl_PlP8UGgdxErlIp8TwuZuI',
    appId: 'YOURAPPID',
    messagingSenderId: '98445333419',
    projectId: 'pushnotificationtest2023',
    storageBucket: 'pushnotificationtest2023.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTzzzvVBoVGoEJ-mI2yAqidfIuvcEk1lA',
    appId: 'YOURAPPID',
    messagingSenderId: '98445333419',
    projectId: 'pushnotificationtest2023',
    storageBucket: 'pushnotificationtest2023.appspot.com',
    iosClientId: '98445333419-bif0otr5kd85u8ehgajo2c27tt7fn1gl.apps.googleusercontent.com',
    iosBundleId: 'com.gbcluster.tetrisMatch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTzzzvVBoVGoEJ-mI2yAqidfIuvcEk1lA',
    appId: 'YOURAPPID',
    messagingSenderId: '98445333419',
    projectId: 'pushnotificationtest2023',
    storageBucket: 'pushnotificationtest2023.appspot.com',
    iosClientId: '98445333419-b4sljlikj6fi77p246savcidfkuc68dd.apps.googleusercontent.com',
    iosBundleId: 'com.gbcluster.tetrisMatch.RunnerTests',
  );
}
